version: '3.2'
services:

  mysql:
    image: mysql
    command:
      - '--max_allowed_packet=256M'
      - '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - 'mysql_databases:/var/lib/mysql'

  drupal:
    image: dcycle/drupal:8drush9
    restart: always
    depends_on:
      - mysql
    volumes:
      - host_config:/etc
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites

volumes:
  host_config:
  mysql_databases:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:

